Views/Home/Index.cshtml, Views/Shared/_Layout.cshtml
=> cambio del hitler

.idea/.idea.Gestper/.idea/.gitignore, .idea/.idea.Gestper/.idea/aws.xml, .idea/.idea.Gestper/.idea/dataSources.local.xml, .idea/.idea.Gestper/.idea/dataSources.xml, .idea/.idea.Gestper/.idea/workspace.xml, Controllers/ticketController.cs, Gestper.csproj, Models/modeloticket.cs, appsettings.json
Cambios ticket en los controladores y modelos
=> cambios ticket

.idea/.idea.Gestper/.idea/dataSources.local.xml, .idea/.idea.Gestper/.idea/dataSources.xml, Controllers/PerfilController.cs, Controllers/UsuarioController.cs, Program.cs, Views/Perfil/index.cshtml, Views/login/login.layout.cshtml, appsettings.json
=> Perfiles de usuarios

.idea/.idea.Gestper/.idea/dataSources.local.xml, .idea/.idea.Gestper/.idea/dataSources.xml, Controllers/PerfilController.cs, Views/Perfil/Editar.cshtml, Views/Perfil/index.cshtml
=> Edicion de perfil

Controllers/NosotrosController.cs, Views/Nosotros/Nosotros.cshtml, Views/Shared/_Layout.cshtml
Se creo el controlador Nosotros, tambien se creo en views la carpeta Nosotros en donde se puso la informacion de Gestper. Se modifico el layaout especificamente el link Nosotros
=> Creacion de Nosotros button

Views/SaberMas/SaberMas.cshtml
Cambio de color en los textos de Saber Mas
=> Cambio de color en Saber Mas

Controllers/ComenzarAhora.cs, Views/ComenzarAhora/ComenzarAhora.cshtml, Views/Home/Index.cshtml
añadi la descripcion del boton de comenzar ahora del home, se creo un controlador de "ComenzarAhora" y un view con el mismo nombre, modificque el index del "Home" para la re direccion del boton
=> Boton de comenzar ahora del home

Views/Shared/_Layout.cshtml
Desaparece el boton de iniciar sesion  una vez pulsado
=> Boton inicio sesion

Controllers/ticketController.cs
Nuevo valor por defecto para prioridad ticket
=> Nuevo valor Prioridad

Views/Home/DetalleTicket.cshtml, Views/Home/IndexAdmin.cshtml
Requerimiento de la Moni: La lista debe tener a primera mano el contacto y tambien en la pantalla de detalle
=> Lista de contactos

Views/Home/IndexAdmin.cshtml
hice cambios en toda la vista del admin.
=> vista panel de admin

Views/Home/IndexAdmin.cshtml
Contactos a primera mano, denuevo porque se perdieron en una  actualizacion
=> Panel admin

Views/Shared/_Layout.cshtml
Reverts CesarValenzuela157/gestper#62
=> Revert "intento de restaurar"

Controllers/HomeControllerTrabajador.cs, Controllers/ticketController.cs, Views/CRUD/crud.lista.cshtml, Views/CRUD/crud.ticket.cshtml, Views/Ticket/Details.cshtml, Views/Ticket/index.cshtml
Mejoras seguimiento en la parte Usuarios.
=> Mejoras seguimiento en la parte Usuarios.

Views/CRUD/crud.ticket.cshtml
=> Mejoras apartado visual

Views/CRUD/crud.ticket.cshtml, Views/Ticket/Create.cshtml
Boton de cerrar sesión agregado a cada pantalla, el boton de Lista de ticket ya no redirige a /Error
=> Corrección errores vista usuario

Views/Ticket/Create.cshtml
se arreglo uno de los problemas mencionados por señora monica el cual era que en el apartado de cliente al crear un ticket si no se llenaban los campos y se intentaba enviar este mandaba un aviso en rojo en ingles, el cual indicaba el deber llenar los campos, se genero la correccion y ahora el mensaje sale en español
=> Cambiofelipe

appsettings.json
=> Correccion error post login

appsettings.json
Reverts CesarValenzuela157/gestper#81
=> Revert "Correccion error post login"

Controllers/ticketController.cs, Views/CRUD/crud.ticket.cshtml
=> Error de controlador para filtro

Views/CRUD/crud.ticket.cshtml
Filtros funcionales y con limpieza de filtros
=> Rediseño de los filtros
